"""create requests table

Revision ID: 00af9ee17791
Revises: 
Create Date: 2026-01-18 18:13:17.438346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00af9ee17791'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('callback_attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('started_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('completed_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('callback_completed_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('callback_time_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
